name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 仅在推送标签时触发（例如：v1.0.0）

jobs:
  build:
    runs-on: ubuntu-latest  # 你可以在这里选择不同的平台，但所有平台将在不同的步骤中构建

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]  # 构建Linux和macOS
        architecture: [amd64, arm64]     # 构建AMD64和ARM64架构

    env:
      APP_NAME: mysql-slow-sql-webhook  # 设置应用程序名称变量

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 检出代码

    - name: Set up Go (如果是Go项目)
      uses: actions/setup-go@v3
      with:
        go-version: '1.23'  # 设置Go版本，根据需要调整

    - name: Build executable
      run: |
        GOARCH=${{ matrix.architecture }} GOOS=${{ matrix.os == 'ubuntu-latest' && 'linux' || 'darwin' }} go build -o $APP_NAME-${GOOS}-${GOARCH} ./cmd/myapp/main.go
        ls -lh $APP_NAME-${GOOS}-${GOARCH}  # 确认构建的文件

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: $APP_NAME-${{ matrix.os }}-${{ matrix.architecture }}
        path: $APP_NAME-${{ matrix.os == 'ubuntu-latest' && 'linux' || 'darwin' }}-${{ matrix.architecture }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 检出代码

    - name: Create GitHub release
      id: create_release
      run: |
        # 获取当前标签
        VERSION=$(echo "${GITHUB_REF}" | sed 's/refs\/tags\///')
        # 创建 GitHub release
        response=$(curl -XPOST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"tag_name": "'"${VERSION}"'", "name": "'"${VERSION}"'", "body": "Release of '${VERSION}'"}' \
          https://api.github.com/repos/${{ github.repository }}/releases)
        # 获取 release ID
        release_id=$(echo $response | jq .id)
        echo "release_id=$release_id" >> $GITHUB_ENV

    - name: Upload assets to GitHub release
      run: |
        VERSION=$(echo "${GITHUB_REF}" | sed 's/refs\/tags\///')
        echo "Uploading build artifacts for release $VERSION"
        # 根据操作系统和架构上传文件
        for file in $APP_NAME-linux-amd64 $APP_NAME-linux-arm64 $APP_NAME-darwin-amd64; do
          if [ -f "$file" ]; then
            echo "Uploading $file"
            curl -XPOST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -F "file=@$file" \
              https://uploads.github.com/repos/${{ github.repository }}/releases/${{ env.release_id }}/assets?name=$(basename $file)
          else
            echo "$file does not exist"
          fi
        done
